local move_acceleration = 3500 
local air_acceleration_factor = 0.8 
local max_speed = 250 
local gravity = -1000 
local jump_takeoff_speed = 400 
local touch_jump_timeout = 0.2 

local group_obstacle = hash("ground") 

function on_message(self, message_id, message, sender)
	if message_id == msg_contact_point_response then 
		if message.group == group_obstacle then 
			handle_obstacle_contact(self, message.normal, message.distance) 
		end 
	end 
end 